#!/usr/bin/env bash
# (This script was written by mkomuro, based on code generated by Google Gemini.)

# --- ヘルプ表示関数 ---
function show_help() {
cat << EOF
Usage: $(basename "$0") [-c CSV_filename] [-o output_epub_folder_name] [-h]

CSV ファイルの情報を読み込み、nepub を実行して EPUB ファイルを作成するスクリプト。

オプション:
  -c CSV_filename        入力 CSV ファイル名を指定します。
                         未指定の場合、'./fetch_list_sample.csv' を使用します。
  -o output_epub_folder_name
                         EPUBファイルの出力先フォルダ名を指定します。
                         未指定の場合、'./epub_data/' を使用します。
                         フォルダが存在しない場合は作成されます。
  -h                     このヘルプメッセージを表示して終了します。

EOF
}
# ------------------------
# 
option_c_arg=""
option_o_arg=""

while getopts ":hc:o:" opt; do
case $opt in
        c)
            # -c オプションが指定された場合（引数あり）
            option_c_arg="$OPTARG"
            ;;
        o)
            # -o オプションが指定された場合（引数あり）
            option_o_arg="$OPTARG"
            ;;
        h)
            # -h オプションが指定された場合（ヘルプ表示）
            show_help
            exit 0
            ;;
        \?)
            # 不正なオプションが指定された場合
            echo "Error: Invalid option -$OPTARG specified." >&2
            echo "Try '$(basename "$0") -h' for more information." >&2
            exit 1
            ;;
        :)
            # オプション引数が不足している場合
            echo "Error: Option -$OPTARG requires an argument." >&2
            echo "Try '$(basename "$0") -h' for more information." >&2
            exit 1
            ;;
    esac
done

# Data directory path (Do not forget adding the last '/')
if [ -z "$option_o_arg" ]; then
    EPUB_DIR=./epub_data/
else
    EPUB_DIR="$option_o_arg"
    # Add '/' if the last character does not end with '/'.
    if [[ "$EPUB_DIR" != */ ]]; then
        EPUB_DIR="${EPUB_DIR}/"
    fi
fi

# If EPUB_DIR doesn't exist, create the direcory.
if [ ! -d ${EPUB_DIR} ]; then
    mkdir -p ${EPUB_DIR}
fi

# Get the CSV file name
if [ -z "$option_c_arg" ]; then
    CSV_FILE=./fetch-list_sample.csv
else
    CSV_FILE="$option_c_arg"
fi

# --- CSVファイルの読み込みと処理 ---
if [ ! -f "$CSV_FILE" ]; then
    echo "Error: The specified CSV file '$CSV_FILE' cannot be found." >&2
    exit 1
fi

# 処理するCSV形式のデータ:
#   For more details, see nepub-dev/scripts/fetch-list_sample.csv.

# CSVファイルからデータを読み込み、空行やコメント行をフィルタリングして処理する
# また、grepで空行（またはコメント行）をフィルタリングする
cat "$CSV_FILE" | grep -v -e '^[[:space:]]*$' -e '^\s*#' | while IFS=, read -r col1 col2 col3; do

    # 各カラムから引用符 (") を削除
    param1=$(echo "$col1" | tr -d '"')
    param2=$(echo "$col2" | tr -d '"')
    param3=$(echo "$col3" | tr -d '"')

    # "小説ID" の先頭がアルファベットで始まっている場合は「narou」
    if [[ "$param1" =~ ^[[:alpha:]] ]]; then
        # nepub コマンド (narou)
        command_line="nepub"
    else
        # nepub コマンド (kakuyomu)
        command_line="nepub -k"
    fi

    # 3番目のカラム ($param3) が空文字列 "" でない場合に指定された nepub オプションを追加
    if [[ -n "$param3" ]]; then
        command_line+=" $param3"
        #command_line+=" -r \"$param3\""
    fi

    # 出力ファイル名: "./nepub_data/タイトル_小説ID.epub"
    output_file="${EPUB_DIR}${param2}_${param1}.epub"

    # 2番目のカラム ($param2) が空文字列 "" でない場合に -o オプションを追加
    if [[ -n "$param2" ]]; then
        command_line+=" -o \"${output_file}\""
    fi

    # 1番目のカラム ($param1) をコマンドの最後に追加
    command_line+=" $param1"

    # 構築されたコマンドを表示
    echo "RUN> $command_line"
    # コマンドの実行
    eval $command_line
    chmod 644 ${output_file}
done

echo -e "\nAll tasks completed. The EPUB file(s) is in folder '${EPUB_DIR}'."
tree -h ${EPUB_DIR}
# --- end of script ---